


pipeline {
    agent any
    

    stages {
        stage('clean and install') {
            steps {
               bat 'mvn clean -f SpringBootProject'
            }
        }
        stage('Package') {
            steps {
               bat 'mvn package'
            }
        }
    }
}
